//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CreateOpportunity.Enterprise {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapBinding", Namespace="urn:enterprise.soap.sforce.com")]
    public partial class SforceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LoginScopeHeader loginScopeHeaderValueField;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private SessionHeader sessionHeaderValueField;
        
        private LimitInfoHeader limitInfoHeaderValueField;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SforceService() {
            this.Url = global::CreateOpportunity.Properties.Settings.Default.CreateOpportunity_Enterprise_SforceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LoginScopeHeader LoginScopeHeaderValue {
            get {
                return this.loginScopeHeaderValueField;
            }
            set {
                this.loginScopeHeaderValueField = value;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public LimitInfoHeader LimitInfoHeaderValue {
            get {
                return this.limitInfoHeaderValueField;
            }
            set {
                this.limitInfoHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginScopeHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:enterprise.soap.sforce.com", ResponseNamespace="urn:enterprise.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public LoginResult login(string username, string password) {
            object[] results = this.Invoke("login", new object[] {
                        username,
                        password});
            return ((LoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password) {
            this.loginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        username,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LimitInfoHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:enterprise.soap.sforce.com", ResponseNamespace="urn:enterprise.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void logout() {
            this.Invoke("logout", new object[0]);
        }
        
        /// <remarks/>
        public void logoutAsync() {
            this.logoutAsync(null);
        }
        
        /// <remarks/>
        public void logoutAsync(object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[0], this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:enterprise.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:enterprise.soap.sforce.com", IsNullable=false)]
    public partial class LoginScopeHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string organizationIdField;
        
        private string portalIdField;
        
        /// <remarks/>
        public string organizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public string portalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:enterprise.soap.sforce.com")]
    public partial class LimitInfo {
        
        private int currentField;
        
        private int limitField;
        
        private string typeField;
        
        /// <remarks/>
        public int current {
            get {
                return this.currentField;
            }
            set {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        public int limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:enterprise.soap.sforce.com")]
    public partial class GetUserInfoResult {
        
        private bool accessibilityModeField;
        
        private bool chatterExternalField;
        
        private string currencySymbolField;
        
        private int orgAttachmentFileSizeLimitField;
        
        private string orgDefaultCurrencyIsoCodeField;
        
        private string orgDefaultCurrencyLocaleField;
        
        private bool orgDisallowHtmlAttachmentsField;
        
        private bool orgHasPersonAccountsField;
        
        private string organizationIdField;
        
        private bool organizationMultiCurrencyField;
        
        private string organizationNameField;
        
        private string profileIdField;
        
        private string roleIdField;
        
        private int sessionSecondsValidField;
        
        private string userDefaultCurrencyIsoCodeField;
        
        private string userEmailField;
        
        private string userFullNameField;
        
        private string userIdField;
        
        private string userLanguageField;
        
        private string userLocaleField;
        
        private string userNameField;
        
        private string userTimeZoneField;
        
        private string userTypeField;
        
        private string userUiSkinField;
        
        /// <remarks/>
        public bool accessibilityMode {
            get {
                return this.accessibilityModeField;
            }
            set {
                this.accessibilityModeField = value;
            }
        }
        
        /// <remarks/>
        public bool chatterExternal {
            get {
                return this.chatterExternalField;
            }
            set {
                this.chatterExternalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currencySymbol {
            get {
                return this.currencySymbolField;
            }
            set {
                this.currencySymbolField = value;
            }
        }
        
        /// <remarks/>
        public int orgAttachmentFileSizeLimit {
            get {
                return this.orgAttachmentFileSizeLimitField;
            }
            set {
                this.orgAttachmentFileSizeLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orgDefaultCurrencyIsoCode {
            get {
                return this.orgDefaultCurrencyIsoCodeField;
            }
            set {
                this.orgDefaultCurrencyIsoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orgDefaultCurrencyLocale {
            get {
                return this.orgDefaultCurrencyLocaleField;
            }
            set {
                this.orgDefaultCurrencyLocaleField = value;
            }
        }
        
        /// <remarks/>
        public bool orgDisallowHtmlAttachments {
            get {
                return this.orgDisallowHtmlAttachmentsField;
            }
            set {
                this.orgDisallowHtmlAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        public bool orgHasPersonAccounts {
            get {
                return this.orgHasPersonAccountsField;
            }
            set {
                this.orgHasPersonAccountsField = value;
            }
        }
        
        /// <remarks/>
        public string organizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public bool organizationMultiCurrency {
            get {
                return this.organizationMultiCurrencyField;
            }
            set {
                this.organizationMultiCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string organizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string profileId {
            get {
                return this.profileIdField;
            }
            set {
                this.profileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string roleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public int sessionSecondsValid {
            get {
                return this.sessionSecondsValidField;
            }
            set {
                this.sessionSecondsValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userDefaultCurrencyIsoCode {
            get {
                return this.userDefaultCurrencyIsoCodeField;
            }
            set {
                this.userDefaultCurrencyIsoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string userEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public string userFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string userLanguage {
            get {
                return this.userLanguageField;
            }
            set {
                this.userLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string userLocale {
            get {
                return this.userLocaleField;
            }
            set {
                this.userLocaleField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string userTimeZone {
            get {
                return this.userTimeZoneField;
            }
            set {
                this.userTimeZoneField = value;
            }
        }
        
        /// <remarks/>
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public string userUiSkin {
            get {
                return this.userUiSkinField;
            }
            set {
                this.userUiSkinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:enterprise.soap.sforce.com")]
    public partial class LoginResult {
        
        private string metadataServerUrlField;
        
        private bool passwordExpiredField;
        
        private bool sandboxField;
        
        private string serverUrlField;
        
        private string sessionIdField;
        
        private string userIdField;
        
        private GetUserInfoResult userInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string metadataServerUrl {
            get {
                return this.metadataServerUrlField;
            }
            set {
                this.metadataServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool passwordExpired {
            get {
                return this.passwordExpiredField;
            }
            set {
                this.passwordExpiredField = value;
            }
        }
        
        /// <remarks/>
        public bool sandbox {
            get {
                return this.sandboxField;
            }
            set {
                this.sandboxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serverUrl {
            get {
                return this.serverUrlField;
            }
            set {
                this.serverUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public GetUserInfoResult userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:enterprise.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:enterprise.soap.sforce.com", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string sessionIdField;
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:enterprise.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:enterprise.soap.sforce.com", IsNullable=false)]
    public partial class LimitInfoHeader : System.Web.Services.Protocols.SoapHeader {
        
        private LimitInfo[] limitInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("limitInfo")]
        public LimitInfo[] limitInfo {
            get {
                return this.limitInfoField;
            }
            set {
                this.limitInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void logoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591